### ISSUE TITLE
log-recent: command not found

### ISSUE THREAD

**Issue by alasdaird** [trengrj/recent#2]
The error "-bash: log-recent: command not found" results after every command line entry. This occurs even after uninstalling. Otherwise great product. would recommend A++++

**Comment by alasdaird** [comment]
I think there may be a conflict with another python package that also uses the command log-recent, based on this output that shows it stopped working after I update the anaconda distribution that contains manay python packages:

2016-10-17 22:07:44 ipython
2016-10-17 22:08:50 conda update conda
2016-10-17 22:09:27 conda update anaconda
2016-10-25 11:58:24 
usage: log-recent [-h] [-r RETURN_VALUE] [-c COMMAND] [-p PID]
log-recent: error: unrecognized arguments:   515  recent 5728 0

**Comment by alasdaird** [comment]
Confirmed that the conflict is with the anaconda package. It has a command for recent and for log-recent.
To prevent the log-recent error appearing I set the variable PROMPT_COMMAND back the Mac default: export PROMPT_COMMAND=update_terminal_cwd

**Comment by trengrj** [comment]
@alasdaird yeah it is annoying if you uninstall, i'll make the default PROMPT_COMMAND to check if log-recent exists first. I think you just need to type `pip install recent --upgrade` and add back the PROMPT_COMMAND to fix.
